name: PyTest

on:
  workflow_dispatch:

jobs:
  pytest:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Python 3
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: mlflow_tasks_dev
          environment-file: environment.yml
          auto-activate-base: false

    - name: Install PyTest
      run: conda install pytest

    - name: Run Pytest
      run: pytest