name: PyTest

on:
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Python 3
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: sudo pip install -r requirements.txt

    - name: Prep conda
      run: sudo conda env create -f environment.yml & sudo conda activate mlflow_tasks_dev

    - name: Install PyTest
      run: sudo pip install pytest

    - name: Run Pytest
      run: sudo pytest