name: PyTest

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  pytest:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Python 3
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: mlflow_tasks_dev
        environment-file: tests/environment.yml
        auto-activate-base: false

    - name: Run Pytest
      run: |
        conda activate mlflow_tasks_dev
        python -m ipykernel install --user --name mlflow_tasks_dev --display-name "mlflow_tasks_dev"
        pytest -W ignore